### ISSUE TITLE
OnScroll || AddEventlistener?

### ISSUE THREAD

**Issue by patrickcerny** [AlpsBTE/alpsbte-website#55]
I've read in a consversation about switching from `window.addEventlistener` to `onScroll`. This may sound good, but if we have another component which reacts onScroll, wont the eventHandler be overwritten? Asking @b3h3m0th and @jokil123 because you two discussed it.

**Comment by b3h3m0th** [comment]
You can just replace `window.addEventlistener` with `window.onscroll`. It achieves the same result. Important difference:
- `window.addEventlistener` adds listeners every time the component rerenders. (see screenshot)
- `window.onscroll`: IS basically the listener. you only define the handler method for it. (which usually is the correct option for such things)

**Comment by patrickcerny** [comment]
@b3h3m0th yea that makes sense, but wont the listener be overwritten if 2 components set the `window.onscroll` function? Or will both be functional?

**Comment by jokil123** [comment]
In default js/ts yes, I even tested inside of the same component (where it was in fact overwritten), but there may be some react stuff in the background I don't know about which allows this (very likely tbh).

Maybe we should instead address the root cause of the problem, which is that we have multiple eventlisteners for the same event. If I remember correctly, eventlisteners should normally be deleted if the page is reloaded.

**Comment by b3h3m0th** [comment]
Sounds good as well

**Comment by patrickcerny** [comment]
Sounds good! Ill create an issue and then link this discussion, first assign first serve i guess 😄
